### ISSUE TITLE
Task-05: Documento de Análisis del Código Fuente y Métricas Asociadas

### ISSUE THREAD

**Issue by lNoelia** [gii-is-psg2/psg2-2122-g6-62#60]

**Comment by javmarjae** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/G6-62-62334cd04f15c300134ac836/issues/gii-is-psg2/psg2-2122-g6-62/60?planning-poker) with ZenHub @Bamtop @domanialv @lNoelia @pedolirod @plss12
