### ISSUE TITLE
Task-04: Documento de Métrica de Proceso Ágil y Recursos

### ISSUE THREAD

**Issue by lNoelia** [gii-is-psg2/psg2-2122-g6-62#61]

**Comment by javmarjae** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/G6-62-62334cd04f15c300134ac836/issues/gii-is-psg2/psg2-2122-g6-62/61?planning-poker) with ZenHub @Bamtop @domanialv @lNoelia @pedolirod @plss12
